$color = rgba(15, 15, 15, 1)
$inner_color = rgba(15, 15, 15, 0.66)
$outer_color = rgba(198, 120, 221, 1)
$font_color = rgba(224, 224, 224, 1)
$placeholder_color = rgba(224, 224, 224, 0.7)
$check_color = rgba(97, 175, 239, 1)
